# Generated by Django 5.1.4 on 2025-05-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_alter_project_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('issued_by', models.CharField(max_length=1000)),
                ('issued_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
