# Generated by Django 5.1.4 on 2025-06-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0010_known_things_hobby_about_hobby_img_alter_hobby_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='more_about',
            name='date',
        ),
        migrations.AddField(
            model_name='more_about',
            name='note',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='more_about',
            name='image',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='more_about',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
