# Generated by Django 5.1.4 on 2025-05-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.PositiveIntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='project',
            name='visit_link',
            field=models.URLField(max_length=10000),
        ),
    ]
