# Generated by Django 5.1.4 on 2025-05-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0003_professionalskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.CharField(max_length=10000),
        ),
    ]
