# Generated by Django 5.1.4 on 2025-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0005_certificates_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='img',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='certificates',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
