# Generated by Django 5.1.4 on 2025-05-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_certificates_img_certificates_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
