# Generated by Django 5.1.4 on 2025-06-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0008_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='more_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='topproj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=10000)),
                ('description', models.TextField()),
                ('visit_link', models.URLField(max_length=10000)),
                ('tech_stack', models.CharField(blank=True, max_length=100, null=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='me.skill')),
            ],
        ),
    ]
