# Generated by Django 5.1.4 on 2025-06-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0009_more_about_topproj'),
    ]

    operations = [
        migrations.CreateModel(
            name='known_things',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hobby',
            name='about',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='img',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
